apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: upg-loadme-hpa
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upg-loadme  # deployment name
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
